### ISSUE TITLE
Problems running Manager

### ISSUE THREAD

**Issue by makdesignlabs** [FioX0/9c-snapshot-manager#4]
I've downloaded the snapshot manager and installed it (not on C drive) as instructed, but when I try to run the program all I get is a quick flash of a box then nothing. It doesn't seem to be updating the snapshot but I'm not sure if there's supposed to be some output when it runs.

I've allowed the program in windows defender firewall as well. Not sure if there's more I can do to get it running. Any suggestions welcomed.

**Comment by FioX0** [comment]
Hi,

Install .net 5.0 ;).

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by FioX0** [comment]
I will be moving the project back to .net 4.X on next release as it seems quite a few PC's simply don't have 5.0 installed.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by makdesignlabs** [comment]
Got the latest 5.0.402 .net installed but still no dice on snapshot manager. Same deal just a quick flash of a box.

**Comment by FioX0** [comment]
Project has been moved back to .net 3.1, it will work if you run V2.
